const menu = [
    {
        id: 1,
        title: "decadent devil's food",
        category: "cakes",
        price: 15.99,
        img: "/images/devil_food_cake.jpg",
        desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.`,
    },
    {
        id: 2,
        title: "lemon lover's dream",
        category: "cakes",
        price: 15.99,
        img: "./images/lemon_cake.jpg",
        desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ultrices, velit at scelerisque ullamcorper, velit tortor ullamcorper.`,
    },
    {
        id: 3,
        title: "strawberries forever",
        category: "cakes",
        price: 15.99,
        img: "./images/strawberry_cake.jpg",
        desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce hendrerit justo quis nibh bibendum, ac malesuada velit fermentum.`,
    },
    {
        id: 4,
        title: "mom's chocolate chip",
        category: "cookies",
        price: 1.99,
        img: "./images/choco_chip.jpg",
        desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce hendrerit justo quis nibh bibendum, ac malesuada velit fermentum.`,
    },
    {
        id: 5,
        title: "mom's double",
        category: "cookies",
        price: 1.99,
        img: "./images/double_chip.jpg",
        desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent convallis, dui eu posuere cursus, purus justo varius metus.`,
    },
    {
        id: 6,
        title: "mom's oatmeal raisin",
        category: "cookies",
        price: 1.99,
        img: "./images/oatmeal_raisin.jpg",
        desc: `Sit amet adipiscing elit, dolor ipsum. Justo malesuada fermentum ligula ut vel. Tortor auctor vivamus sed.`,
    },
    {
        id: 7,
        title: "mom's double delight",
        category: "cupcakes",
        price: 3.99,
        img: "./images/choc_cupcake.jpg",
        desc: `Sit amet adipiscing elit, dolor ipsum. Commodo fermentum id nunc. Vestibulum ullamcorper, justo nunc.`,
    },
    {
        id: 8,
        title: "strawberry sensation",
        category: "cupcakes",
        price: 3.99,
        img: "./images/straw_cupcake.jpg",
        desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.`,
    },
    {
        id: 9,
        title: "oreo red velvet",
        category: "cupcakes",
        price: 3.99,
        img: "./images/velvet_cupcake.jpg",
        desc: `Lorem ipsum dolor amet, elit consectetur adipiscing. Nunc fermentum commodo, id ullamcorper vestibulum.`,
    },
    {
        id: 10,
        title: "mom's cherry",
        category: "pies",
        price: 12.99,
        img: "./images/cherry_pie.jpg",
        desc: `Adipiscing elit, dolor sit amet. Vestibulum ullamcorper, commodo fermentum nunc. Consectetur adipiscing elit.`,
    },
    {
        id: 11,
        title: "mom's caramel apple",
        category: "pies",
        price: 12.99,
        img: "./images/apple_pie.jpg",
        desc: `Sit amet, consectetur adipiscing elit. Nunc ullamcorper, fermentum commodo. Dolor ipsum elit.`,
    },
    {
        id: 12,
        title: "mom's peachy peach",
        category: "pies",
        price: 12.99,
        img: "./images/peach_pie.jpg",
        desc: `Lorem ipsum dolor sit, consectetur adipiscing elit. Nunc ullamcorper, fermentum commodo justo.`,
    },
];

export default menu;