const menu = [
    {
        id: 1,
        title: "decadent devil's food",
        category: "cakes",
        price: 15.99,
        img: "https://i.ytimg.com/vi/4EalxubjcA8/maxresdefault.jpg",
        desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.`,
    },
    {
        id: 2,
        title: "lemon lover's dream",
        category: "cakes",
        price: 15.99,
        img: "https://www.mealsbymolly.com/wp-content/uploads/2021/03/Lemon-Cake.jpg.webp",
        desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ultrices, velit at scelerisque ullamcorper, velit tortor ullamcorper.`,
    },
    {
        id: 3,
        title: "strawberries forever",
        category: "cakes",
        price: 15.99,
        img: "https://amycakesbakes.com/wp-content/uploads/2021/07/Fresh-Strawberry-Cake-by-Amycakes-Bakes.jpg",
        desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce hendrerit justo quis nibh bibendum, ac malesuada velit fermentum`,
    },
    {
        id: 4,
        title: "mom's chocolate chip",
        category: "cookies",
        price: 1.99,
        img: "https://www.tastesoflizzyt.com/wp-content/uploads/2022/01/potato-chip-cookies-insta-1200x799.jpg",
        desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce hendrerit justo quis nibh bibendum, ac malesuada velit fermentum`,
    },
    {
        id: 5,
        title: "mom's double",
        category: "cookies",
        price: 1.99,
        img: "https://theglutenfreeaustrian.com/wp-content/uploads/2023/01/doublechocolate11-720x405.jpg",
        desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent convallis, dui eu posuere cursus, purus justo varius metus.`,
    },
    {
        id: 6,
        title: "mom's oatmeal raisin",
        category: "cookies",
        price: 1.99,
        img: "https://previews.dropbox.com/p/thumb/ACL7uZ813iy1h079wqCEx4a3Gl_3EYfPFk56Gn9SWEEZMW8b8bMfTJHpuBZaUku6XETgLKOTV4FuoPclUcmOWNxrwyeXxiJBCsir5rUCcI6105jCmVUNGUEg1_-TbYAeV34eBYZwzkjyVCzt-niKKQjGDZKg8q_D2YrWgidqcc7MDiZARO3ybyRXEQzpcCniH88khJCSO3m2vGwBUIeh-iDKpr6CiIhm3qvdEUecrWZu1jIyhJbC_oJJrL-bhx_UEz4KQ6Ma_jp6hI_Lr_KJMe68qkNhb-rdgJV8khux8r1Es81js_GR2PxGVQ3JaEIWnXef4U6K7CibWhrk0H5AtfjiyiAHAfIBOxImF0NOrIZ0zA/p.jpeg",
        desc: `Sit amet adipiscing elit, dolor ipsum. Justo malesuada fermentum ligula ut vel. Tortor auctor vivamus sed.`,
    },
    {
        id: 7,
        title: "mom's double delight",
        category: "cupcakes",
        price: 3.99,
        img: "https://thescranline.com/wp-content/uploads/2023/04/CHOCOLATE-CUPCAKES-S-01.jpg",
        desc: `Sit amet adipiscing elit, dolor ipsum. Commodo fermentum id nunc. Vestibulum ullamcorper, justo nunc.`,
    },
    {
        id: 8,
        title: "mom's strawberry sensation",
        category: "cupcakes",
        price: 3.99,
        img: "https://preppykitchen.com/wp-content/uploads/2022/07/Strawberry-Cupcakes-Recipe-Card.jpg",
        desc: ``,
    },
    {
        id: 9,
        title: "oreo red velvet",
        category: "cupcakes",
        price: 3.99,
        img: "https://corasfamilykitchen.com/wp-content/uploads/2018/08/306BD0D4-3059-4FC0-A036-6029DA2BEBF9.jpeg",
        desc: `Lorem ipsum dolor amet, elit consectetur adipiscing. Nunc fermentum commodo, id ullamcorper vestibulum.`,
    },
    {
        id: 10,
        title: "mom's cherry",
        category: "pies",
        price: 12.99,
        img: "https://w4s8p5t8.rocketcdn.me/wp-content/uploads/2022/06/vegan-cherry-pie-23.jpg",
        desc: `Adipiscing elit, dolor sit amet. Vestibulum ullamcorper, commodo fermentum nunc. Consectetur adipiscing elit.`,
    },
    {
        id: 11,
        title: "mom's caramel apple",
        category: "pies",
        price: 12.99,
        img: "https://houseofnasheats.com/wp-content/uploads/2021/11/Salted-Caramel-Apple-Pie-1.jpg",
        desc: `Sit amet, consectetur adipiscing elit. Nunc ullamcorper, fermentum commodo. Dolor ipsum elit.`,
    },
    {
        id: 12,
        title: "mom's peachy peach",
        category: "pies",
        price: 12.99,
        img: "https://www.savoryexperiments.com/wp-content/uploads/2022/07/Southern-Peach-Pie-16.jpg",
        desc: `Lorem ipsum dolor sit, consectetur adipiscing elit. Nunc ullamcorper, fermentum commodo justo.`,
    },
];

export default menu;